spring:
  application:
    name: ExpiryWatch
  datasource:
    url: ${DB_URL:jdbc:postgresql://db.dgyweiviwcgmigyhuwar.supabase.co:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:"[ExpiryWatch 123456789]"}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      connection-timeout: 20000
      keepalive-time: 45000
  thymeleaf:
    cache: true
  web:
    resources:
      cache:
        period: 86400
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}
  tomcat:
    max-http-form-post-size: 10485760

gmail:
  client-id: ${GMAIL_CLIENT_ID:some-default-id}
  client-secret: ${GMAIL_CLIENT_SECRET:some-default-secret}
  refresh-token: ${GMAIL_REFRESH_TOKEN:some-default-token}